CREATE TABLE IF NOT EXISTS patients (
    patient_id VARCHAR(20) PRIMARY KEY,
    nic_number VARCHAR(20) NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    date_of_birth DATE NOT NULL,
    gender ENUM('Male', 'Female', 'Other') NOT NULL,
    phone_number VARCHAR(20) NOT NULL,
    email VARCHAR(120),
    blood_group VARCHAR(5),
    address VARCHAR(255),
    city VARCHAR(80),
    district VARCHAR(80),
    emergency_contact_name VARCHAR(120),
    emergency_contact_phone VARCHAR(20),
    emergency_contact_relation VARCHAR(80),
    password_hash VARCHAR(255),
    portal_active BOOLEAN NOT NULL DEFAULT 0,
    portal_last_login TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_patients_nic (nic_number),
    INDEX idx_patients_phone (phone_number),
    INDEX idx_patients_email (email),
    INDEX idx_patients_name (last_name, first_name)
);
